// <auto-generated />
using GrpcServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GrpcServer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220712080334_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GrpcServer.Model.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Email = "mykola.karpenko@brightstar-academy.com",
                            FirstName = "Mykola",
                            LastName = "Karpenko"
                        },
                        new
                        {
                            StudentId = 2,
                            Email = "nina.vyzir@brightstar-academy.com",
                            FirstName = "Nina",
                            LastName = "Vyzir"
                        },
                        new
                        {
                            StudentId = 3,
                            Email = "oleksandr.yevtushenko@brightstar-academy.com",
                            FirstName = "Oleksandr",
                            LastName = "Yevtushenko"
                        },
                        new
                        {
                            StudentId = 4,
                            Email = "roman.shyrin@brightstar-academy.com",
                            FirstName = "Roman",
                            LastName = "Shyrin"
                        },
                        new
                        {
                            StudentId = 5,
                            Email = "viktor.kozhyn@brightstar-academy.com",
                            FirstName = "Viktor",
                            LastName = "Кozhyn"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
